In [2]:
import pandas

In [4]:
dataset = pandas.read_csv('data.csv')
dataset

,STATE,REGION_TYPE,RESPONSE_STATUS,AGE_GROUP,INCOME_GROUP,OCCUPATION_GROUP,EDUCATION_GROUP,GENDER_GROUP,POWER_GROUP,TRAVEL_GROUP,...,WILL_BUY_TWO_WHEELER_OF_TYPE,WILL_BUY_TWO_WHEELER_NOW,GOOD_TIME_TO_BUY_TWO_WHEELER,HAS_OUTSTANDING_SAVING_IN_FIXED_DEPOSITS,HAS_OUTSTANDING_BORROWING,BORROWED_FOR_CONSUMPTION_EXPENDITURE,BORROWED_FOR_CONSUMER_DURABLES,BORROWED_FOR_VEHICLES,BORROWED_FROM_BANK,BORROWED_FROM_BANK_FOR_VEHICLES
0,West Bengal,RURAL,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Graduates minority household,Balanced,24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,Y,Y,N,N,N,N
1,Assam,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Telangana,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Wage Labourers,Graduates minority household,Male Dominated,24 hours,30-60 minutes,...,Not Applicable,Y,NaN,N,Y,Y,N,N,N,N
3,Odisha,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Haryana,URBAN,Accepted,Grown-up - dominant,150000 - 200000,Entrepreneurs,Households of all literates,Male Majority,24 hours,15-30 minutes,...,Not Applicable,N,NaN,N,Y,N,Y,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Assam,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Matriculates majority household,Female Majority,12-24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,N,N,N,N,N,N
96,Gujarat,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Maharashtra,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Haryana,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Gujarat,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# What percentage of sample households have only one two wheeler ? (2DF)
q1 = dataset["TWO_WHEELERS_OWNED"].where(dataset["TWO_WHEELERS_OWNED"] == 1).count() / dataset["TWO_WHEELERS_OWNED"].count() * 100
q1 # need to check because do we need to consider the households with no two wheelers

67.74193548387096

In [21]:
# What percentage of sample households don't have a two wheeler, but are interested in buying one?
intereted = dataset.loc[dataset["WILL_BUY_TWO_WHEELER"] == "Y"].count().iloc[0]
no_two_wheeler = dataset.loc[dataset["TWO_WHEELERS_OWNED"] == 0].count().iloc[0]
q2 = intereted / no_two_wheeler * 100
q2

88.23529411764706

In [22]:
# What percentage of sample households already have a two wheeler, but are interested in buying one more?
two_wheeler = dataset.loc[dataset["TWO_WHEELERS_OWNED"] > 0].count().iloc[0]
interested = dataset.loc[dataset["WILL_BUY_TWO_WHEELER_NOW"] == "Y"].count().iloc[0]
q3 = interested / two_wheeler * 100
q3

26.666666666666668

In [24]:
# What percentage of urban households don't have a two wheeler, but are intending to buy immediately?
urban = dataset.loc[dataset["REGION_TYPE"] == "URBAN"].count().iloc[0]
immediate = dataset.loc[dataset["REGION_TYPE"] == "URBAN"].where(dataset["WILL_BUY_TWO_WHEELER_NOW"] == "Y").count().iloc[0]
q4 = immediate / urban * 100
q4

13.157894736842104

In [ ]:
# Based on the sample data, what is the existing market share of Commuter bikes?

In [ ]:
# What percentage of Female majority/ Female dominant / Only Female households have a scooter ?
female_majority = dataset.loc[dataset["GENDER_GROUP"] in [""]]