In [84]:
import pandas

In [85]:
dataset = pandas.read_csv('data.csv')
dataset

,STATE,REGION_TYPE,RESPONSE_STATUS,AGE_GROUP,INCOME_GROUP,OCCUPATION_GROUP,EDUCATION_GROUP,GENDER_GROUP,POWER_GROUP,TRAVEL_GROUP,...,WILL_BUY_TWO_WHEELER_OF_TYPE,WILL_BUY_TWO_WHEELER_NOW,GOOD_TIME_TO_BUY_TWO_WHEELER,HAS_OUTSTANDING_SAVING_IN_FIXED_DEPOSITS,HAS_OUTSTANDING_BORROWING,BORROWED_FOR_CONSUMPTION_EXPENDITURE,BORROWED_FOR_CONSUMER_DURABLES,BORROWED_FOR_VEHICLES,BORROWED_FROM_BANK,BORROWED_FROM_BANK_FOR_VEHICLES
0,West Bengal,RURAL,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Graduates minority household,Balanced,24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,Y,Y,N,N,N,N
1,Assam,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Telangana,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Wage Labourers,Graduates minority household,Male Dominated,24 hours,30-60 minutes,...,Not Applicable,Y,NaN,N,Y,Y,N,N,N,N
3,Odisha,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Haryana,URBAN,Accepted,Grown-up - dominant,150000 - 200000,Entrepreneurs,Households of all literates,Male Majority,24 hours,15-30 minutes,...,Not Applicable,N,NaN,N,Y,N,Y,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Assam,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Matriculates majority household,Female Majority,12-24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,N,N,N,N,N,N
96,Gujarat,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Maharashtra,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Haryana,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Gujarat,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
# dataset.dropna(inplace=True)
dataset

,STATE,REGION_TYPE,RESPONSE_STATUS,AGE_GROUP,INCOME_GROUP,OCCUPATION_GROUP,EDUCATION_GROUP,GENDER_GROUP,POWER_GROUP,TRAVEL_GROUP,...,WILL_BUY_TWO_WHEELER_OF_TYPE,WILL_BUY_TWO_WHEELER_NOW,GOOD_TIME_TO_BUY_TWO_WHEELER,HAS_OUTSTANDING_SAVING_IN_FIXED_DEPOSITS,HAS_OUTSTANDING_BORROWING,BORROWED_FOR_CONSUMPTION_EXPENDITURE,BORROWED_FOR_CONSUMER_DURABLES,BORROWED_FOR_VEHICLES,BORROWED_FROM_BANK,BORROWED_FROM_BANK_FOR_VEHICLES
0,West Bengal,RURAL,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Graduates minority household,Balanced,24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,Y,Y,N,N,N,N
1,Assam,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Telangana,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Wage Labourers,Graduates minority household,Male Dominated,24 hours,30-60 minutes,...,Not Applicable,Y,NaN,N,Y,Y,N,N,N,N
3,Odisha,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Haryana,URBAN,Accepted,Grown-up - dominant,150000 - 200000,Entrepreneurs,Households of all literates,Male Majority,24 hours,15-30 minutes,...,Not Applicable,N,NaN,N,Y,N,Y,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Assam,URBAN,Accepted,Grown-up - dominant,200000 - 250000,Self-employed Entrepreneurs,Matriculates majority household,Female Majority,12-24 hours,15-30 minutes,...,Not Applicable,N,NaN,Y,N,N,N,N,N,N
96,Gujarat,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Maharashtra,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Haryana,RURAL,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Gujarat,URBAN,Non-Response,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,Data Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
# What percentage of sample households have only one two wheeler ? (2DF)
q1 = dataset["TWO_WHEELERS_OWNED"].where(dataset["TWO_WHEELERS_OWNED"] == 1).count() / dataset["TWO_WHEELERS_OWNED"].count()
q1 = f"{q1:.2f}"
print(q1)

0.68

In [88]:
# What percentage of sample households don't have a two wheeler, but are interested in buying one?
no_two_wheeler = dataset.where(dataset["TWO_WHEELERS_OWNED"] == 0)
interested = no_two_wheeler["WILL_BUY_TWO_WHEELER"].where(no_two_wheeler["WILL_BUY_TWO_WHEELER"] == "Y").count()
q2 = (interested / no_two_wheeler.count()).iloc[0]
q2 = f"{q2:.2f}"
print(q2)

0.24

In [89]:
# What percentage of sample households already have a two wheeler, but are interested in buying one more?
no_two_wheeler = dataset.where(dataset["TWO_WHEELERS_OWNED"] > 0)
interested = no_two_wheeler["WILL_BUY_TWO_WHEELER"].where(no_two_wheeler["WILL_BUY_TWO_WHEELER"] == "Y").count()
q3 = (interested / no_two_wheeler.count()).iloc[0]
q3 = f"{q3:.2f}"
print(q3)

0.24

In [90]:
# What percentage of urban households don't have a two wheeler, but are intending to buy immediately?
urban = dataset.loc[dataset["REGION_TYPE"] == "URBAN"].count().iloc[0]
immediate = dataset.loc[dataset["REGION_TYPE"] == "URBAN"].where(dataset["WILL_BUY_TWO_WHEELER_NOW"] == "Y").count().iloc[0]
q4 = immediate / urban
q4 = f"{q4:.2f}"
print(q4)

0.13

In [91]:
# Based on the sample data, what is the existing market share of Commuter bikes?
bikes_owned = dataset.where(dataset["TYPE_OF_TWO_WHEELER_OWNED"] != "Not Applicable")
commuter_bikes = bikes_owned.where(bikes_owned["TYPE_OF_TWO_WHEELER_OWNED"] == "Commuter Bike").count().iloc[0]
total_bikes = bikes_owned.count().iloc[0]
q5 = commuter_bikes / total_bikes
q5 = f"{q5:.2f}"
print(q5)

0.39

In [92]:
# What percentage of Female majority/ Female dominant / Only Female households have a scooter ?
female_majority = dataset.loc[(dataset["GENDER_GROUP"] == "Female Majority") | (dataset["GENDER_GROUP"] == "Female Dominated") | (dataset["GENDER_GROUP"] == "Only Female"), ["TYPE_OF_TWO_WHEELER_OWNED"]]
scooter = female_majority.where(dataset["TYPE_OF_TWO_WHEELER_OWNED"] == "Scooter").count().iloc[0]
q6 = scooter / female_majority.count().iloc[0]
q6 = f"{q6:.2f}"
print(q6)

0.25

In [93]:
# If having an outstanding loan disqualifies the eligibility for a new loan, how many households (%) are eligible for a new loan?
eligible = dataset.loc[dataset["HAS_OUTSTANDING_BORROWING"] == "N"].count().iloc[0]
q7 = eligible / dataset["HAS_OUTSTANDING_BORROWING"].count()
q7 = f"{q7:.2f}"
print(q7)

0.61

In [94]:
# A Bank is willing to provide loans at a lower interest rate if the borrower is willing to pledge a FD as security for the loan. What percentage of households who want to buy a two wheeler would be eligible for a lower interest loan against FD?
wanting = dataset.loc[dataset["WILL_BUY_TWO_WHEELER"] == "Y"]
fds = wanting.loc[dataset["HAS_OUTSTANDING_SAVING_IN_FIXED_DEPOSITS"] == "Y"].count().iloc[0]
wanting = wanting.count().iloc[0]
q8 = fds / wanting
q8 = f"{q8:.2f}"
print(q8)

0.53

In [102]:
# # Calculate target market share for electric two wheelers
electric = dataset[dataset["POWER_GROUP"] == "24 hours"]
two_wheeler = electric.loc[dataset["WILL_BUY_TWO_WHEELER"] == "Y"].count().iloc[0]
total = electric.count().iloc[0]
q9 = two_wheeler / total
q9 = f"{q9:.2f}"
print(q9)

0.27

In [101]:
# Calculate percentage of Rural Farmers with at least one two wheeler
rural_farmers = dataset.loc[(dataset["REGION_TYPE"] == "RURAL") & (dataset["OCCUPATION_GROUP"].str.contains("Farmers"))]
two_wheeler = rural_farmers.loc[rural_farmers["TWO_WHEELERS_OWNED"] > 0].count().iloc[0]
total = rural_farmers.count().iloc[0]
q10 = two_wheeler / total * 100
q10 = f"{q10:.2f}"
print(q10)

100.00

In [103]:
answers = [q1, q2, q3, q4, q5, q6, q7, q8, q9, q10]
output = "\n".join([f"Q{i},{answers[i-1]}" for i in range(1, 11)])
dataset_number = 56 # change this to the dataset number
import os
roll = os.environ.get("IITM_ROLL_NUMBER")
with open(f"{roll}_GA1_Dataset{dataset_number}.csv", "w") as f:
    f.write(output)